language: python
python:
  - "3.7"
cache: pip
env: 
  - DJANGO=1.11.24
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source='.' manage.py test -v 2
  - flake8 .
after_success:
  - coveralls
