# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_account_name', models.CharField(max_length=80)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('signed_date', models.DateField()),
            ],
        ),
    ]
