# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='gtf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='GTF'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='gts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='GTS'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='upfront_projection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Upfront'),
        ),
    ]
