# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='link_to_salesforce_case',
            field=models.CharField(max_length=120),
        ),
    ]
