# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recoup', models.BooleanField()),
                ('status', models.CharField(choices=[('COMMITED/APPROVED', 'COMMITED/APPROVED'), ('PENDING', 'PENDING')], max_length=80)),
                ('upfront_projection', models.DecimalField(decimal_places=10, max_digits=19)),
                ('maximum_payment_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('recoup_amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('gtf', models.DecimalField(decimal_places=10, max_digits=19)),
                ('gts', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
