# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='event_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='gtf',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='installment',
            name='gts',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='installment',
            name='recoup_amount',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='installment',
            name='upfront_projection',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
