# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191101_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='gtf',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='gts',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='maximum_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='recoup_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, choices=[('COMMITED/APPROVED', 'COMMITED/APPROVED'), ('PENDING', 'PENDING')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='upfront_projection',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
