# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Contract'),
            preserve_default=False,
        ),
    ]
