# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190925_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='user_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
