# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-31 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_installmentcondition_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentcondition',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'png', 'jpeg', 'jpg'])]),
        ),
    ]
