# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191016_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentcondition',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Installment'),
        ),
    ]
