# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contract_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='case_number',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='salesforce_case_id',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='salesforce_id',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
