# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191003_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentcondition',
            name='done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
