# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190923_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='contract_id',
            new_name='contract',
        ),
    ]
