# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-29 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191028_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='event_id',
        ),
    ]
