INVALID_SIGN_DATE = '5678'
INVALID_RECOUP_AMOUNT = '1234A'
INVALID_PAYMENT_DATE = '28 DE OCTUBRE'

INSTALLMENT_CONDITIONS = [
    ('START_SALES', 'START SALES'),
    ('PROMISSORY_NOTE', 'PROMISSORY NOTE'),
    ('SALES_REACH', 'SALES REACH'),
]

SF_LOGIN_URL = "https://test.salesforce.com/services/oauth2/token"

STATUS = [
    ('COMMITED/APPROVED', 'COMMITED/APPROVED'),
    ('PENDING', 'PENDING'),
]
