INVALID_SIGN_DATE = '5678'
INVALID_RECOUP_AMOUNT = '1234A'
INVALID_PAYMENT_DATE = '28 DE OCTUBRE'

STATUS = [
    ('COMMITED/APPROVED', 'COMMITED/APPROVED'),
    ('PENDING', 'PENDING'),
]

INSTALLMENT_CONDITIONS = [
    ('START_SALES', 'START SALES'),
    ('PROMISSORY_NOTE', 'PROMISSORY NOTE'),
    ('SALES_REACH', 'SALES REACH'),

]